### ISSUE TITLE
Broken on 1.13.10

### ISSUE THREAD

**Issue by mjanda** [ember-data/active-model-adapter#62]
I think c2564d45a27da7e3525693d1f37af07373538213 broke it for me.

```Uncaught TypeError: Cannot read property 'validateFullName' of undefined``` in Registry.register()

**Comment by Arkham** [comment]
Opened a PR to fix this: https://github.com/ember-data/active-model-adapter/pull/63

**Comment by kenips** [comment]
I'm still seeing this on released 2.0.2.

**Comment by jcope2013** [comment]
@kenips what version of ember data and ember are you using?

**Comment by kenips** [comment]
Ember @ `1.13.10` and ED @ `1.13.11`

**Comment by jcope2013** [comment]
you need to use the 1.13.6 branch of active model adapter as the 2.0+ has stuff specific to ember data 2.0+, basically rule of thumb seems to be not mixing 2.0 and 1.13 of ember core libraries in an app, that being said there could be potential backport of stuff into a 1.13.7 if someone makes a good case

**Comment by kenips** [comment]
Hmm that's news to me. I'd hope that 2.0.x to be compatible with Ember 1.13.x as long as depredations are removed (and this is what we are working on, removing depreciations and moving to 2.0.x for all Ember packages). This particular bug and PR (#63) indicates that 1.13.x support is still being worked on (or at least considered).

It might be pure coincident that 2.0.0 and 2.0.1 work with 1.13.x and 2.0.2 doesn't. Since I am upgrading from 2.0.1 my assumption is quite obvious that this is indeed a bug! That's ok. I'll stick to 2.0.1 for now and get to 1.13.7 of there is one (not anything particular atm needs backporting).

**Comment by typeoneerror** [comment]
> you need to use the 1.13.6 version of active model adapter as the 2.0+ has stuff specific to ember data 2.0+

@jcope2013 @kenips also seeing this error with Ember 2.0.2, ED 2.0.1 and AMA 2.0.2, so it's the above seems to not be true?
