### ISSUE TITLE
Resetting the Ember app breaks with "cannot re-register: adapter:-active-model".

### ISSUE THREAD

**Issue by kaukas** [ember-data/active-model-adapter#77]
Hello.

I am trying to use `active-model-adapter` in a project and set the tests up. I want to reset the Ember app before every test (which I believe is the best practice) but I get an error about re-registering the `active-model-adapter`. I have reduced the test case to [this fiddle](https://jsfiddle.net/qmg3surj/). It complains:
```
Error: Cannot re-register: `adapter:-active-model`, as it has already been resolved.
```
Could you please help me understand what I am doing wrong? Thank you!

**Comment by fivetanley** [comment]
This is an issue in Ember itself, not super specific to ActiveModelAdapter. I think an issue could be opened there.

You can workaround it by doing what the `ember-cli` scaffold does for you:

```javascript

module('le test', {
  beforeEach: function() {
    App = startApp();
  },
  afterEach: function() {
    Ember.run(App, 'destroy');
  }
});
```

Instead of using `reset`, `destroy` seems to work. I agree this is a bug but it's not something we can fix inside of AMA. It would have to be fixed in Ember.
